create table PAR_PARTICIPANTS (PRJ_ID bigint not null, PER_ID bigint not null, constraint PK_PAR primary key (PRJ_ID, PER_ID)) in TSAPP4; 

create table PER_PERSON (PER_ID bigint generated by default as identity (start with 1), PER_DT_BIRTH varbinary(255), PER_NM_CELLPHONE varchar(255), PER_ST_FIRST_NAME varchar(255), PER_ST_LAST_NAME varchar(255), constraint PK_PER primary key (PER_ID)) in TSAPP4; 

create table PRJ_PROJECT (PRJ_ID bigint generated by default as identity (start with 1), PRJ_DT_BEGIN varbinary(255), PRJ_DT_END varbinary(255), PRJ_ST_NAME varchar(255), PRJ_ST_STATUS integer, constraint PK_PRJ primary key (PRJ_ID)) in TSAPP4; 

alter table PAR_PARTICIPANTS add constraint IRPRJPAR foreign key (PRJ_ID) references PRJ_PROJECT; 

alter table PAR_PARTICIPANTS add constraint IRPERPAR foreign key (PER_ID) references PER_PERSON; 

grant select on PAR_PARTICIPANTS to GAPPDR; 

grant select on PER_PERSON to GAPPDR; 

grant select on PRJ_PROJECT to GAPPDR; 

grant delete, insert, select, update on PAR_PARTICIPANTS to GAPPDW; 

grant delete, insert, select, update on PER_PERSON to GAPPDW; 

grant delete, insert, select, update on PRJ_PROJECT to GAPPDW; 

create index APP.FKPARPER on PAR_PARTICIPANTS (PER_ID) allow reverse scans; 

create index APP.FKPARPRJ on PAR_PARTICIPANTS (PRJ_ID) allow reverse scans; 

-- Content of this file is appended in generated SQL file 

